### PR TITLE
Support for multiple controllers

### PR DESCRIPTION
**Pull request by SambraveTheWise**
Plugin can now handle multiple controllers (specified by NUM_CONTROLLERS). Instead of attempting to retrieve controller input from localhost:8082/, it now appends the index of the given controller that it's looking for input from. For example, "localhost:8082/0" for the first controller, "localhost:8082/1" for the second controller, etc.

### CODE REVIEW

**Review by kevinhughes27 — APPROVED** [review]
Hey! Thanks for the PR, the code looks great 😄 

Does the emulator always see 4 controllers when using this plugin now? I wonder if we might want to make that configurable to allow for some emulated controllers and some real ones. Can I ask what you're using this for? Is it with TensorKart or the mupen64plus gym?

The next question I have is how are we going to ship - I think the gym project just pulls master which will break now since it won't append the the `/0` to the url until we change it ([code here](https://github.com/bzier/gym-mupen64plus/blob/master/gym_mupen64plus/envs/mupen64plus_env.py#L212)). There might be other dependent projects as well. We haven't really had to think about versioning or anything yet. Open to ideas here cc @bzier

**Comment by bzier** [comment]
The Dockerfile for gym-mupen64plus uses [a specific commit hash](https://github.com/bzier/gym-mupen64plus/blob/28de76ec4d9a9377dae80ff5853d11ddb69ee72b/Dockerfile#L34), so no worries there; shouldn't break it. We can update that whenever we make the change. We may want to create an issue in that repo to track it.

**Comment by kevinhughes27** [comment]
Excellent! I'll wait to hear back about how the emulator handles the 4 controllers then we can ship and update at out leisure.

**Comment by SambraveTheWise** [comment]
Yes, the emulator always sees 4 controllers now (if NUM_CONTROLLERS was set to 3, the emulator would only see 3 controllers, etc - any change to NUM_CONTROLLERS would require the project to be built again).

And for compatibility's sake, if need be, the URL for the first controller could be set to '/' (instead of '/0'), while keeping the additional controllers the same (e.g. /1, /2, /3).

I'm using this project to implement network play for n64. I've played over the network using Project64k before, but the issue with that is it can get out of sync. On Project64k, an emulator runs on each user's machine, and I believe it just sends controls back and forth - but since there are multiple sources of truth (e.g. two or more emulators, depending on how many players are connected), and there's no way to keep the emulators in sync, any small amount of lag on one end throws things off.

My idea is to have the emulator on one machine (e.g. hosted on a server), and then user's controls are sent to the server (currently I'm using a web page with socket.io for this - and the Node.js backend is what serves the JSON to this plugin). Later I'll be figuring out how to stream back the audio and video to the same web page. (so basically the web page is currently the n64 controller, and the server is the n64 game console - and when I get the audio/video streaming figured out, the web page will also act as the TV). I plan on adding on-screen controls so a smartphone could be used as the controller.

In the future I want to be able to have spectators in the room, be able to "hand a controller" over to one of the spectators, etc. AI could also be added in the future, which would send data to the Node.js backend (instead of user input from the web page).

I'm not sure how well my idea will be performance-wise, but I'm experimenting with things to see how they work.

**Comment by kevinhughes27** [comment]
Sounds like a very cool project! I'd love to hear how it turns out 😸 

I'm going to merge this and if we find a need to configure the number of controllers in the future we'll deal with it then.

Thanks for your contribution!

**Pull request merged**
